### PR TITLE
Add Mods: No50s and No100s

### PR DESCRIPTION
**Pull request by JTF195**
This was totally trivial to implement compared to when I did it on osu!lazer

### CODE REVIEW

**Comment by McKay42** [comment]
Looking good, two very minor things:
1. OsuHUD::drawHitErrorBar() should also reflect the mods, take a look at how it handles the ming3012 mod
2. The list of experimental mods would now be too long for the minimum "supported" resolution of 800x600, so buttons would get cut off. Putting the label+buttons into a CBaseUIScrollView would fix that (currently all buttons and the label are just in a primitive CBaseUIContainer, m_experimentalContainer)

I know my GUI framework is not very good (was originally only meant for debugging), so it's probably better if I add the scrollView myself. I'll merge after you make the modifications to drawHitErrorBar()

**Comment by JTF195** [comment]
I left the hit error bar alone as a design choice.

The MinG3012 mod doesn't change the min/max hit timing window, so size and behavior of the hit error bar doesn't change - it just loses a section

The No100s and No50s mods _do_ change the hit timing window, so there are two ways it could be changed:

1. Maintain the overall size of the hit error bar by extending the size of the remaining sections, but resulting in inconsistent placement of hit/miss lines

2. Maintain the consistent placement of hit/miss lines and the size of the 300/100 sections by simply cutting the 50/100 sections, but sacrifice the consistent overall size of the bar

I don't really like either of those solutions, plus I think the way it works is handy in that the miss/overtap lines tell you what the hit _would have been_

**Comment by JTF195** [comment]
I'm not opposed to changing it, but it needs to work in a consistent and intuitive way.

Maybe I could change the 100/50 sections to red instead of removing them?

**Comment by JTF195** [comment]
Incidentally, the hit error bar isn't properly being adjusted with HT/DT according to the following table:
https://w.ppy.sh/8/88/ODTable.png

I'll see if I can get that working too.

**Comment by JTF195** [comment]
I don't personally like showing the entire miss window on the hit error bar either, but I do think it might be useful to add sometime later as an option, so I didn't totally nuke the code.

I went with a hybrid approach, which can be changed to 'option 2' above by commenting out another 2 lines of code

**Comment by McKay42** [comment]
You can make it into a ConVar that's set to false by default, that would be good. Optional stuff that users can configure is always ok, but changing the default is not so good I think.

**Comment by JTF195** [comment]
There. That _should_ be everything, finally

**Comment by JTF195** [comment]
I think that's done and ready to review

By the way, when I implemented the mods in lazer last fall, I actually made them a two-mode toggle (like DT/NC) and I made icons for them:

selection-mod-no50s 2x selection-mod-no100s 2x

I saw somewhere you mentioned you had no intention of making icons for all/any of the experimental mods, but I'd be willing to make a few for the more useful mods, just to give them a bit more visibility.

**Comment by McKay42** [comment]
There is still one unused mod slot with the current grid size, that could be used for these two mods (or we make the grid bigger like they did for ScoreV2).
Thanks for the PR, go for it if you want to make mod icons :)

(I'm not worried too much about design or aesthetics if that wasn't obvious enough from the main menu, but not sure about using the official osu! mod icon style here)

**Pull request merged**
