### PR TITLE
Update OsuGameRules.cpp

### PR DESCRIPTION
**Pull request by Toyeonjeangikkingkkang**
Change a fast AR

### CODE REVIEW

**Comment by McKay42** [comment]
Why do you want this merged? (ConVars can be customized via the [in-game console or cfgs](https://steamcommunity.com/app/607260/discussions/0/1620599015885400990/))

**Comment by Toyeonjeangikkingkkang** [comment]
Hello. Because I want to Changed Because I want to double the AR time,
And I want to be free to adjust the speed of the HP Drain reduction rate at will, regardless of spinner additions, spinner duration, new combos, note density, OD, etc.

**Comment by McKay42** [comment]
> Because I want to Changed Because I want to double the AR time, And I want to be free to adjust the speed of the HP Drain reduction rate at will, regardless of spinner additions, spinner duration, new combos, note density, OD, etc.

You don't have to recompile the game in order to change ConVars, you can change them via the [in-game console or cfgs](https://steamcommunity.com/app/607260/discussions/0/1620599015885400990/):
Capture1
Capture2

Hit SHIFT + F1 to open the console and just change the values.

**Comment by Toyeonjeangikkingkkang** [comment]
Thank you. How can I Find a Developer Console(Shift+F1) on McOsuNX?

**Comment by McKay42** [comment]
> Thank you. How can I Find a Developer Console(Shift+F1) on McOsuNX?

While you are holding X pressed, click the right thumbstick to toggle the in-game console.
To get a keyboard, just click the right thumbstick alone, same as you would for text search in the songbrowser.
To execute the entered command press A.

**However**, as this is a bit tedious on the switch, it's probably a better idea to just _permanently_ add your changes to `/<sdcard>/switch/McOsu/cfg/osu.cfg`. Just open it with a text editor and add whatever commands you want at the bottom of the file. (If you don't do this then the commands will reset if you close the game.)

**Comment by Toyeonjeangikkingkkang** [comment]
Hello, McKay. How can freely adjust the speed of the HP Drain reduction rate at will, regardless of spinner additions, spinner duration, new combos, note density, OD, etc.?

**Pull request closed without merging**
